<a href="https://colab.research.google.com/github/varadarajan1/DeepLearning-Practice/blob/master/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Types

In [0]:
! ls

sample_data


Add **!** in front to exceute shell commands

In [0]:
name = "iPhone 5s"

In [0]:
type(name)

str

In [0]:
print(name)

iPhone 5s


In [0]:
number_of_speakers = 10

In [0]:
type(number_of_speakers)

int

In [0]:
print("I bought a new "+ name)

I bought a new iPhone 5s


In [0]:
a = 3
b= 2
print(a+b, a-b, a/b, a//b, a**b)


5 1 1.5 1 9


In [0]:
screen_size=5.7

In [0]:
print(screen_size)

5.7


In [0]:
is_android = False

In [0]:
type(is_android)

bool

In [0]:
print(is_android==True)

False


In [0]:
print(is_android==False and number_of_speakers>2)

True


# Code blocks - If,For,While

In [0]:
if(is_android == True):
  print(name+"supports android")
  print("Still inside android block")
print("Outside if block")

Outside if block


In [0]:
for i in range(5):
  print(i,i*i)

0 0
1 1
2 4
3 9
4 16


In [0]:
i=0
while i<=10:
  print(i,i*i)
  i+=1

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100


In [0]:
def print_squares(number:int):
  for i in range(number):
    print(i,i*i)

# Functions

In [0]:
print_squares(4)

0 0
1 1
2 4
3 9


In [0]:
def sum_of_squares(number:int)->int:
  sum=0
  for i in range(number):
    sum+=i*i
  return sum

In [0]:
sum_of_squares(5)

30

In [0]:
sum_5 = sum_of_squares(5)
print(sum_5)

30


In [0]:
def print_with_startVal(stop_val,start_val=0):
  """Prints squares of numbers between start_val(inclusive) and stop_val(exclusive)"""
  for i in range(start_val, stop_val):
    print(i, i*i)

In [0]:
print_with_startVal(5)

0 0
1 1
2 4
3 9
4 16


In [0]:
print_with_startVal(5,1)

1 1
2 4
3 9
4 16


In [0]:
help(print_with_startVal)

Help on function print_with_startVal in module __main__:

print_with_startVal(stop_val, start_val=0)
    Prints squares of numbers between start_val(inclusive) and stop_val(exclusive)



# Lists

In [0]:
my_phone=[name, is_android, screen_size]

In [0]:
type(my_phone)

list

In [0]:
print(my_phone)

['iPhone 5s', False, 5.7]


In [0]:
my_phone[1:3]

[False, 5.7]

In [0]:
my_dad_phone = my_phone
print(my_dad_phone)

['iPhone 5s', False, 5.7]


In [0]:
my_phone[0]

'iPhone 5s'

In [0]:
my_phone[2]=4

In [0]:
print(my_dad_phone)

['iPhone 5s', False, 4]


Deep Copy

In [0]:
my_dad_phone = list(my_phone)

In [0]:
my_phone[0]='iPhone 7S'
print(my_phone)
print(my_dad_phone)

['iPhone 7S', False, 5.7]
['iPhone 5s', False, 5.7]


In [0]:
len(my_phone)

3

In [0]:
my_phone.append("3G")
len(my_phone)

4

Append a *list* to a *list*

In [0]:
some_prefs = ["Single sim",100]

In [0]:
my_phone+=some_prefs

In [0]:
for i in my_phone:
  print(i)

iPhone 7S
False
5.7
3G
Single sim
100


In [0]:
range(5)

range(0, 5)

In [0]:
a = list(range(5))

In [0]:
b = list(map(lambda x: x**2, a))
print(b)

[0, 1, 4, 9, 16]


In [0]:
c = list(filter(lambda x: x%2==0,b))
print(c)

[0, 4, 16]


# Tuples, Sets and Dictionaries


In [0]:
my_tuple = ('iPhone 5s', False, 4.3)
print(my_tuple)

('iPhone 5s', False, 4.3)


In [0]:
for data in my_tuple:
  print(data)

iPhone 5s
False
4.3


In [0]:
# Tuples are immutable. This will throw an error
my_tuple[1] = True 

TypeError: ignored

In [0]:
import time

In [0]:
tic = time.time()
print(tic)

1567428256.8362336


In [0]:
time.time?

In [0]:
tic = time.time()
# Do some task
toc = time.time()
print("Time elapsed:",toc-tic)

Time elapsed: 4.458427429199219e-05


In [0]:
a = list(range(1000000))
tic = time.time()
b = list(map(lambda x:x*x,a))
toc = time.time()
print("Elapsed time:",toc-tic)

Elapsed time: 0.14019203186035156


In [0]:
# Tuples are faster
a = tuple(range(1000000))
tic = time.time()
b = list(map(lambda x:x*x,a))
toc = time.time()
print("Elapsed time:",toc-tic)

Elapsed time: 0.12270593643188477


In [0]:
# Sets don't allow duplicates
my_set = set(my_phone)
print(my_set)

{False, 100, 5.7, 'iPhone 7S', '3G', 'Single sim'}


In [0]:
my_phone.append(5.7)
my_set = set(my_phone)
print(my_set)

{False, 100, 5.7, 'iPhone 7S', '3G', 'Single sim'}


In [0]:
my_phone_dic = {}
type(my_phone_dic)

dict

In [0]:
my_phone_dic["name"]="iPhone 5s"
my_phone_dic["isAndroid"]=True
my_phone_dic["screenSize"]= 4.3
print(my_phone_dic)

{'name': 'iPhone 5s', 'isAndroid': True, 'screenSize': 4.3}


In [0]:
my_phone_dic["screenSize"]

4.3

In [0]:
my_phone_dic.values()

dict_values(['iPhone 5s', True, 4.3])

In [0]:
my_phone_dic.keys()

dict_keys(['name', 'isAndroid', 'screenSize'])

In [0]:
for key in my_phone_dic.keys():
  print(key,my_phone_dic[key])

name iPhone 5s
isAndroid True
screenSize 4.3


# Packages

In [0]:
import math
a = math.sqrt(4)
print(a)

2.0


In [0]:
b = math.pow(2,2)

In [0]:
import math as m
print(m.factorial(10))

3628800


In [0]:
from math import factorial
print(factorial(10))

3628800


In [0]:
! echo 'def hello():''' > my_first_module.py
! echo '  print("Hello, I am from a different file")' >>  my_first_module.py

In [0]:
import my_first_module
my_first_module.hello()

Hello, I am from a different file


In [0]:
from my_first_module import hello
hello()

# File Handling

In [0]:
!wget https://s3.amazonaws.com/thinkific-import/153034/mobile_cleaned-1549119762886.csv

--2019-09-02 14:17:54--  https://s3.amazonaws.com/thinkific-import/153034/mobile_cleaned-1549119762886.csv
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.147.5
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.147.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14044 (14K) [text/csv]
Saving to: ‘mobile_cleaned-1549119762886.csv’

mobile_cleaned-1549 100%[===================>]  13.71K  --.-KB/s    in 0s      

2019-09-02 14:17:54 (153 MB/s) - ‘mobile_cleaned-1549119762886.csv’ saved [14044/14044]



In [0]:
file = open("mobile_cleaned-1549119762886.csv",'r')
print(file.readline())

sim_type,aperture,gpu_rank,weight,stand_by_time,processor_frequency,thickness,flash_type,front_camera_resolution,auto_focus,screen_size,frames_per_second,FM,no_of_reviews_in_gsmarena_in_week,os,phone_height,screen_protection,sim_size,price,talk_time,video_resolution,display_resolution,removable_battery,display_type,primary_camera_resolution,battery_type,ram_memory,internal_memory,brand_rank,no_of_cores,micro_sd_slot,screen_pixel_density,water_proof_rate,phone_width,expandable_memory,version,usb_type,battery_capacity,processor_rank,is_liked



In [0]:
file.close()

In [0]:
with open("mobile_cleaned-1549119762886.csv",'r') as file:
   for line in file:
      print(line)

In [0]:
with open("mobile_cleaned-1549119762886.csv",'r') as file:
   for line in file:
      for word in line.split(','):
        print(word)
      print("--------------")

In [0]:
with open("test_output.txt",'w') as file:
    file.write("Hello world")

In [0]:
!cat test_output.txt

Hello world

# Python Class

In [0]:
class MobilePhone:
  """This class holds details of the mobile phone"""
  def __init__(self, name, is_Android = False, screen_size=5.4):
    self.name = name
    self.is_Android = is_Android
    self.screen_size = screen_size
    self.ratings = -1
  
  def has_ratings(self)->bool:
    return self.ratings>-1

In [0]:
new_phone = MobilePhone("iPhone5s")
print(new_phone.name, new_phone.is_Android, new_phone.screen_size)

iPhone5s False 5.4


In [0]:
print(new_phone.has_ratings())
new_phone.ratings=5
print(new_phone.has_ratings())

True
True


In [0]:
MobilePhone.__doc__

'This class holds details of the mobile phone'

Inheritance in Python

In [0]:
class iPhone

# NumPy

In [0]:
import numpy as np

In [10]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [11]:
type(x)

numpy.ndarray

In [13]:
l = [1,2,3]
x = np.asarray(l)
print(l)

[1, 2, 3]


In [15]:
x = np.asarray(l,float)
print(x)

[1. 2. 3.]


In [17]:
x.shape

(3,)

In [0]:
 # help
np.array?

In [23]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
x[1,2]

6

In [27]:
x[1,0:3]

array([4, 5, 6])

In [29]:
x[0,:]

array([1, 2, 3])

In [0]:
x=np.zeros((4,5))

In [34]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
x = np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
x = np.random.random((4,5))
print(x)

[[0.40252157 0.49813788 0.55055269 0.09332161 0.59507414]
 [0.8145468  0.54946849 0.90184683 0.65761508 0.24758623]
 [0.74685283 0.73069679 0.86173966 0.98331783 0.62280525]
 [0.95563197 0.56133036 0.53755673 0.69408871 0.52203585]]


In [45]:
# Transpose
z = x.T
print(z)

[[0.40252157 0.8145468  0.74685283 0.95563197]
 [0.49813788 0.54946849 0.73069679 0.56133036]
 [0.55055269 0.90184683 0.86173966 0.53755673]
 [0.09332161 0.65761508 0.98331783 0.69408871]
 [0.59507414 0.24758623 0.62280525 0.52203585]]


In [50]:
y = x.reshape(20,1)
print(y)

[[0.40252157]
 [0.49813788]
 [0.55055269]
 [0.09332161]
 [0.59507414]
 [0.8145468 ]
 [0.54946849]
 [0.90184683]
 [0.65761508]
 [0.24758623]
 [0.74685283]
 [0.73069679]
 [0.86173966]
 [0.98331783]
 [0.62280525]
 [0.95563197]
 [0.56133036]
 [0.53755673]
 [0.69408871]
 [0.52203585]]


In [52]:
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [53]:
B = np.arange(5)
C = A+B
D = A-B
E = A * B
print(C,D,E)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [54]:
print(A, A+1)

[0 1 2 3 4] [1 2 3 4 5]


In [55]:
A = np.random.random([2,4])
print(A)
print(A+1)

[[0.30692887 0.70213922 0.18593442 0.87604573]
 [0.38258269 0.81450966 0.91734153 0.54877468]]
[[1.30692887 1.70213922 1.18593442 1.87604573]
 [1.38258269 1.81450966 1.91734153 1.54877468]]


In [57]:
A = np.floor(np.random.np.random.random([2,3])*10)
print(A)

[[1. 7. 5.]
 [1. 9. 8.]]


In [60]:
u = [1,2,3]
v =[-1,0,1]

p1 = np.inner(u,v)
print(p1)

2


In [62]:
p2 = np.outer(u,v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [64]:
A = np.ones([2,3])
B = np.ones((3,2))
np.dot(A,B)

array([[3., 3.],
       [3., 3.]])

In [68]:
np.dot(B.T,A.T)

array([[3., 3.],
       [3., 3.]])

In [71]:
A.sum()

6.0

In [74]:
A.sum(axis = 0)

array([2., 2., 2.])

In [76]:
A.sum(axis = 1)

array([3., 3.])

In [77]:
A.max()

1.0